name: Restore Azure PostgreSQL

on:
  workflow_dispatch:  # Allows manual trigger
    inputs:
      resource_group:
        description: "Azure Resource Group"
        required: true
        default: "NetworkWatcherRG"
      source_server:
        description: "Source PostgreSQL Server Name"
        required: true
        default: "labaitest"
      new_server:
        description: "New Restored Server Name"
        required: true
        default: "labaitest-restored"
permissions:
  id-token: write
  contents: read
jobs:
  restore_pgsql:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      - name: Restore PostgreSQL Server
        run: |
          echo "Restoring ${{ github.event.inputs.source_server }} to new server ${{ github.event.inputs.new_server }}..."
          
          az postgres flexible-server restore \
            --resource-group ${{ github.event.inputs.resource_group }} \
            --name ${{ github.event.inputs.new_server }} \
            --source-server ${{ github.event.inputs.source_server }}

          echo "✅ PostgreSQL Restore Completed Successfully!"

      - name: Completion Message
        run: echo "✅ PostgreSQL Restore Completed Successfully!"
