name: Deploy AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy AKS with Bicep
        run: |
          az deployment group create \
            --name aks-deployment \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --template-file bicep/main.bicep \
            --parameters @parameters.json
