name: AZ Login

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'The name of the resource group'
        required: true
      vault_name:
        description: 'The name of the backup vault'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  create-backup-vault:
    name: Azure Login
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: List all resource groups
        run: |
          az group list --output table
