name: Delete Azure Resource Group Resources

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Azure Resource Group Name'
        required: true
        type: string
permissions:
  id-token: write
  contents: read
jobs:
  list-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: List Resources in Resource Group
        run: |
          echo "Fetching all resources under the resource group: ${{ github.event.inputs.resource_group }}"
          az resource list --resource-group ${{ github.event.inputs.resource_group }} --output table

  delete-resources:
    runs-on: ubuntu-latest
    needs: list-resources
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Delete Resources One by One
        run: |
          RG_NAME="${{ github.event.inputs.resource_group }}"
          echo "Fetching resources in $RG_NAME..."
          RESOURCES=$(az resource list --resource-group $RG_NAME --query "[].id" -o tsv)

          if [ -z "$RESOURCES" ]; then
            echo "No resources found in $RG_NAME."
            exit 0

          for RESOURCE_ID in $RESOURCES; do
            echo "Deleting $RESOURCE_ID..."
            az resource delete --ids "$RESOURCE_ID"
            if [ $? -eq 0 ]; then
              echo "Successfully deleted $RESOURCE_ID"
            else
              echo "Failed to delete $RESOURCE_ID"
      
