name: Azure Disk Management

on:
    workflow_dispatch:
        inputs:
            activity:
                description: 'Activity to perform (create, attach, detach, delete)'
                required: true
                type: choice
                options:
                    - create
                    - attach
                    - detach
                    - delete
            resource_group:
                description: 'Resource Group Name'
                required: true
                type: string
            vm_name:
                description: 'Name of the Virtual Machine (Required for attach/detach)'
                required: false
                type: string
            disk_name:
                description: 'Name of the Disk'
                required: true
                type: string
            disk_size:
                description: 'Disk Size in GB (Required for create)'
                required: false
                type: number
            disk_sku:
                description: 'Disk SKU (Required for create - Standard_LRS, Premium_LRS, etc.)'
                required: false
                type: string

jobs:
    manage-disk:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Perform Disk Management
              run: |
                  ACTIVITY="${{ github.event.inputs.activity }}"
                  RESOURCE_GROUP="${{ github.event.inputs.resource_group }}"
                  VM_NAME="${{ github.event.inputs.vm_name }}"
                  DISK_NAME="${{ github.event.inputs.disk_name }}"
                  DISK_SIZE="${{ github.event.inputs.disk_size }}"
                  DISK_SKU="${{ github.event.inputs.disk_sku }}"

                  if [[ "$ACTIVITY" == "create" ]]; then
                      echo "Creating disk $DISK_NAME with size $DISK_SIZE GB and SKU $DISK_SKU..."
                      az disk create --resource-group "$RESOURCE_GROUP" --name "$DISK_NAME" --size-gb "$DISK_SIZE" --sku "$DISK_SKU"

                  elif [[ "$ACTIVITY" == "attach" ]]; then
                      if [[ -z "$VM_NAME" ]]; then
                          echo "VM Name is required for attaching a disk!"
                          exit 1
                      fi
                      echo "Attaching disk $DISK_NAME to VM $VM_NAME..."
                      az vm disk attach --resource-group "$RESOURCE_GROUP" --vm-name "$VM_NAME" --name "$DISK_NAME"

                  elif [[ "$ACTIVITY" == "detach" ]]; then
                      if [[ -z "$VM_NAME" ]]; then
                          echo "VM Name is required for detaching a disk!"
                          exit 1
                      fi
                      echo "Detaching disk $DISK_NAME from VM $VM_NAME..."
                      az vm disk detach --resource-group "$RESOURCE_GROUP" --vm-name "$VM_NAME" --name "$DISK_NAME"

                  elif [[ "$ACTIVITY" == "delete" ]]; then
                      echo "Deleting disk $DISK_NAME..."
                      az disk delete --resource-group "$RESOURCE_GROUP" --name "$DISK_NAME" --yes

                  else
                      echo "Invalid activity: $ACTIVITY"
                      exit 1
                  fi
