name: Workflow to deploy WordPress Virtual Machine on Azure

on:
  workflow_dispatch:
    inputs:
      admin-username:
        description: 'Admin Username'
        required: true
        default: 'default-username'
      admin-password:
        description: 'Admin Password'
        required: true
        default: 'default-password'
      resource-group-name:
        description: 'Resource Group Name'
        required: true
        default: 'default-rg'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-resources-to-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Deploy WordPress on an Azure Virtual Machine
        uses: Azure/WordPress-Azure-VirtualMachine@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ github.event.inputs['resource-group-name'] }}
          admin-username: ${{ github.event.inputs['admin-username'] }}
          admin-password: ${{ github.event.inputs['admin-password'] }}
