name: Assign Backup Vault MSI Role

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource Group Name'
        required: true
      vault_name:
        description: 'Backup Vault Name'
        required: true
      pgsql_server_name:
        description: 'PostgreSQL Flexible Server Name'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  assign-msi-roles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Assign MSI Role to Backup Vault
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            VAULT_NAME="${{ github.event.inputs.vault_name }}"
            RG_NAME="${{ github.event.inputs.resource_group }}"
            PGSQL_SERVER_NAME="${{ github.event.inputs.pgsql_server_name }}"

            echo "Getting Vault MSI..."
            VAULT_MSI=$(az dataprotection backup-vault show \
              --vault-name $VAULT_NAME  \
              --resource-group $RG_NAME \
              --query identity.principalId -o tsv)

            echo "Vault MSI: $VAULT_MSI"

            echo "Getting PostgreSQL server ID..."
            PGSQL_SCOPE=$(az postgres flexible-server show \
              --name $PGSQL_SERVER_NAME \
              --resource-group $RG_NAME \
              --query id -o tsv)

            echo "Assigning Contributor role to Vault MSI on PostgreSQL server..."
            az role assignment create \
              --assignee $VAULT_MSI \
              --role "Contributor" \
              --scope $PGSQL_SCOPE

            echo "Getting Resource Group ID..."
            RG_SCOPE=$(az group show --name $RG_NAME --query id -o tsv)

            echo "Assigning Contributor role to Vault MSI on RG..."
            az role assignment create \
              --assignee $VAULT_MSI \
              --role "Contributor" \
              --scope $RG_SCOPE

            echo "Role assignments completed successfully!"
